version: '2'

services:
  db:
    image: mongo:latest
    volumes:
      - invisibledata:/data/db
  storyteller:
    build:
      context: .
      dockerfile: Dockerfile-story
    environment:
      mongodb: mongodb://db/ivl
    volumes:
      - invisibleapp:/usr/src/app
    ports:
      - 7000:7000
    depends_on:
      - db
  vigile:
    image: node:6
    environment:
      mongodb: mongodb://db/ivl
    command: ["npm","run","vigile"]
    volumes_from:
      - storyteller
    working_dir: /usr/src/app
    ports:
      - 7200:7200
    depends_on:
      - db
      - storyteller
  exposer:
    image: node:6
    environment:
      mongodb: mongodb://db/ivl
    command: ["npm","run","exposer"]
    volumes_from:
      - storyteller
    working_dir: /usr/src/app
    ports:
      - 7300:7300
    depends_on:
      - db
      - storyteller
  #chopsticks:
    # image:

volumes:
  invisibledata:
  invisibleapp:
