db:
  image: mongo:latest
  #env_file: nombredb.env
  volumes:
    - invisibledata:/data/db
app:
  build: .
  ports:
    - 7000:7000
#  volumes:
#    - invisibleapp:/usr/src/app 
  links:
    - db
#vigile:
#  image: node:6
#  ports:
#    - 7200:7200
#exposer:
#  image: node:6
#  ports:
#    - 7300:7300
